<!DOCTYPE html>
<html>
	<head>
		<?php echo $this->getChildHtml('head'); ?>
	</head>
	<body>
		<div data-role="page">
			<?php echo $this->getChildHtml('after_body_start'); ?>
			<div id="container" class="container">
				<?php echo $this->getChildHtml('notices'); ?>
				<div id="header" data-role="header">
					<?php echo $this->getChildHtml('header'); ?>
				</div>
				<div id="content" data-role="content">
					<?php echo $this->getChildHtml('breadcrumbs'); ?>
					<?php echo $this->getChildHtml('content'); ?>
				</div>
				<div id="footer" data-role="footer">
					<?php echo $this->getChildHtml('footer'); ?>
				</div>
			</div>
		</div>

		<div data-role="page" id="mainmenu">
			<?php echo $this->getChildHtml('mainmenu');?>
		</div>

		<div id="messages" data-role="page">
			<?php echo $this->getChildHtml('messages'); ?>
		</div>
	</body>
</html>