<ul data-role="listview">
	<li data-role="list-divider">Intro</li>
	<li><a href=""><?php echo $this->__('What is ZeroG?'); ?></a></li>
	<li data-role="list-divider">Dwelve in</li>
	<li><a href=""><?php echo $this->__('Installing ZeroG'); ?></a></li>
	<li><a href=""><?php echo $this->__('Creating your first extension'); ?></a></li>
	<li><a href=""><?php echo $this->__('Often used functions/helpers'); ?></a></li>
</ul>