<ul class="listview">
	<li class="list-divider">Intro</li>
	<li><a href=""><?php echo $this->__('What is ZeroG?'); ?></a></li>
	<li class="list-divider">Dwelve in</li>
	<li><a href=""><?php echo $this->__('Installing ZeroG'); ?></a></li>
	<li><a href=""><?php echo $this->__('Creating your first extension'); ?></a></li>
	<li><a href=""><?php echo $this->__('Often used functions/helpers'); ?></a></li>
</ul>