<ul class="listview" class="listview-extensions">
	<li class="fieldcontain">
		<label for="search-extensions"><?php echo $this->__('Search for extensions:'); ?></label>
		<input type="search" name="search-extensions" id="search-extensions" value="" />
	</li>
	<li class="fieldcontain">
		<fieldset class="controlgroup horizontal">
			<legend><?php echo $this->__('Sort by'); ?></legend>
			<a href="index.html"><?php echo $this->__('Date'); ?></a>
			<a href="index.html"><?php echo $this->__('Popularity'); ?></a>
		</fieldset>
	</li>
	<li class="list-divider"><?php echo $this->__('Browse by categories'); ?></li>
	<li>
		<a href="">Commerce <span class="ui-li-count">1</span></a>
		<ul>
			<li>
				<a href="">
					<img src="<?php echo $this->getSkinUrl('images/icon.png'); ?>" class="ui-li-icon" />
					<h3>Commerce (Pixelplant_Commerce 0.1.1)</h3>
					<p><em>adăugaţi un magazin online pe site.</em></p>
					<p>dezvoltat de: Radu Mogoş, www.pixelplant.ro</p>
					<p class="ui-li-aside">3 review-uri</p>
				</a>
			</li>
		</ul>
	</li>
	<li>
		<a href="">Social media <span class="ui-li-count">1</span></a>
		<ul>
			<li>
				<a href="">
					<img src="<?php echo $this->getSkinUrl('images/icon.png'); ?>" class="ui-li-icon" />
					<h3>Social (Pixelplant_Social 0.1.1)</h3>
					<p><em>adăugaţi un magazin online pe site.</em></p>
					<p>dezvoltat de: Radu Mogoş, www.pixelplant.ro</p>
					<p class="ui-li-aside">3 review-uri</p>
				</a>
			</li>
		</ul>
	</li>
	<li>
		<a href="">Content <span class="ui-li-count">3</span></a>
		<ul>
			<li>
				<a href="">
					<img src="<?php echo $this->getSkinUrl('images/icon.png'); ?>" class="ui-li-icon" />
					<h3>Cms (Pixelplant_Cms 0.1.1)</h3>
					<p><em>adăugaţi un magazin online pe site.</em></p>
					<p>dezvoltat de: Radu Mogoş, www.pixelplant.ro</p>
					<p class="ui-li-aside">3 review-uri</p>
				</a>
			</li>
			<li>
				<a href="">
					<img src="<?php echo $this->getSkinUrl('images/icon.png'); ?>" class="ui-li-icon" />
					<h3>Commerce (Pixelplant_Commerce 0.1.1)</h3>
					<p><em>adăugaţi un magazin online pe site.</em></p>
					<p>dezvoltat de: Radu Mogoş, www.pixelplant.ro</p>
					<p class="ui-li-aside">3 review-uri</p>
				</a>
			</li>
			<li>
				<a href="">
					<img src="<?php echo $this->getSkinUrl('images/icon.png'); ?>" class="ui-li-icon" />
					<h3>Slider (Pixelplant_Slider 0.1.1)</h3>
					<p><em>adăugaţi un magazin online pe site.</em></p>
					<p>dezvoltat de: Radu Mogoş, www.pixelplant.ro</p>
					<p class="ui-li-aside">3 review-uri</p>
				</a>
			</li>
		</ul>
	</li>
	<li>
		<a href="">Search <span class="ui-li-count">0</span></a>
	</li>
</ul>