<?php $_elements = $this->getChildren(); ?>


<?php if ($_elements): ?>
<div class="form-fieldset">
	<div class="form-fieldset-header">
		<h3><?php echo $this->getHeader(); ?></h3>
	</div>
	<div class="form-fieldset-content">
		<table class="form-fieldset-table">
			<tbody>
			<?php foreach ($_elements as $_element): ?>
				<tr class="form-field">
					<?php echo $_element->getContent(); ?>
				</tr>
			<?php endforeach; ?>
			</tbody>
		</table>
	</div>
</div>
<?php endif; ?>