<div class="inner">
<h1>
	<a href=""><img src="<?php echo $this->getSkinUrl('images/logo.png'); ?>" alt="" /></a>
	<span id="ajax_worker" style="display: none"><img src="<?php echo $this->getSkinUrl('images/ajax-loader.gif'); ?>" alt=""/></span>
</h1>
<div id="header_nav">
	<div class="header_nav_wrap">
		<div class="avatar">
			<a href="index.html"><img alt="<?php echo $this->__('User thumbnail'); ?>" height="30" src="<?php echo $this->getMediaUrl('avatar/avatar1.gif'); ?>" style=" height:30px; width:30px;" width="30" /></a>
		</div>
		<ul>
			<li><a href="">radu.mogos@abcnet.ch</a></li>
			<li>
				<ul class="links">
					<li><a href="/settings">Settings</a></li>
					<li><a href="/settings">Logout</a></li>
				</ul>
			</li>
		</ul>
	</div>
</div>
<?php echo $this->getChildHtml('mainmenu');?>
</div>