<h1><?php echo $this->__('ZeroG Admin Skin'); ?></h1>
<div id="header_nav">
	<div id="header_nav">
		<div class="avatar">
			<a href="index.html"><?php echo $this->__('User thumbnail'); ?><img alt="Avatar_user" height="30" src="<?php echo $this->getSkinUrl(); ?>/images/icons/avatar.png" style=" height:30px; width:30px;" width="30" /></a>
		</div>
		<ul>
			<li><a href="">me@me.com</a></li>
			<li>
				<ul class="links">
					<li><a href="/settings">Settings</a></li>
					<li></li>
				</ul>
			</li>
		</ul>
	</div>
</div>
<?php echo $this->getChildHtml('mainmenu');?>