<div class="section">
	<div class="section_header">
		<h3>Right side</h3>
	</div>
	<div class="section_content">
		<ul>
			<li><a href="">Read all the details</a></li>
			<li>Last change: 12.01.2012</li>
		</ul>
	</div>
</div>
<div class="section">
	<div class="section_header">
		<h3>Right side</h3>
	</div>
	<div class="section_content">
		<p>Test</p>
	</div>
</div>
<div class="section">
	<div class="section_header">
		<h3>Right side</h3>
	</div>
	<div class="section_content">
		<p>Test</p>
	</div>
</div>
<div class="section">
	<div class="section_header">
		<h3>Right side</h3>
	</div>
	<div class="section_content">
		<p>Test</p>
	</div>
</div>
