<div data-role="header" data-theme="d">
	<h1>Dialog</h1>
</div>
<div data-role="content" data-theme="c">
	<h1>Delete page?</h1>
	<p>This is a regular page, styled as a dialog. To create a dialog, just link to a normal page and include a transition and <code>data-rel="dialog"</code> attribute.</p>
	<a href="docs-dialogs.html" data-role="button" data-rel="back" data-theme="b">Sounds good</a>
	<a href="docs-dialogs.html" data-role="button" data-rel="back" data-theme="c">Cancel</a>
</div>