<?php var_dump(\Z::getRequest()->getParams());?>
<a data-role="button" href="#messages" data-rel="dialog"><?php echo $this->__('Open the popup'); ?></a>
<form method="post" action="<?php echo $this->getUrl('page/view/index'); ?>">
	<h2>Test form</h2>
	<div data-role="fieldcontain">
		<label for="testInput">Test POST</label>
		<input type="text" name="testInput" id="testInput" />
	</div>
	<input type="submit" name="testSubmit" value="Send"/>
</form>
<h2>ZeroG Features</h2>
<div data-role="collapsible">
   <h3><?php echo $this->__('PHP 5.3 support (namespaces, SPL, etc)'); ?></h3>
   <p>Yes, namespaces. Not "_" (underscore) characters used as separators so
	   you can mimic namespaces.
   </p>
   <p>
	   namespace App\Code\Local\Pixelplant\Blog\Blocks {}
   </p>
</div>
<div data-role="collapsible">
   <h3><?php echo $this->__('Easily build extensions'); ?></h3>
   <p>If you've built extensions for Magento, then building extensions for ZeroG 
	   will be a breeze for you. If you haven't, then go ahead and
	   <a href="">read the docs</a></p>
</div>
<div data-role="collapsible">
   <h3><?php echo $this->__('Modifiable design packages, themes and skins'); ?></h3>
   <p>Built on a system similar to that of Magento's. If you follow the same
	   structure and already know how to define your xml layout files then you're
	   already in business with ZeroG</p>
</div>
<div data-role="collapsible">
   <h3>jQuery + jQuery mobile support built in</h3>
   <p>I'm the collapsible content with a themed content block set to "A".</p>
</div>
<?php foreach ($this->getBlogCollection() as $post): ?>
	<div data-role="collapsible">
		<h3><?php echo $post->getTitle(); ?></h3>
		<p><?php echo $post->getPostContent(); ?></p>
	</div>
<?php endforeach; ?>