<div id="blog_accordion" class="blog_accordion">
    <h3><a href="#">Latest pending comments</a></h3>
    <div>
		<ol>
			<li style="margin: .4em 0">
				<p>
					<span style="float:right">
						<a href="">Publish</a>
						<a href="">Delete</a>
					</span>
					<a href="">Lorem ipsum dolor sit amec...</a>
				</p>
				<p><sup>13/02/2012, by gringo@test.com</sup></p>
				<p>The progress bar is designed to simply display the current % complete for a process. The bar is coded to be flexibly sized through CSS and will scale... </p>
			</li>
			<li style="margin: .4em 0">
				<p>
					<span style="float:right">
						<a href="">Publish</a>
						<a href="">Delete</a>
					</span>
					<a href="">Lorem ipsum dolor sit amec...</a>
				</p>
				<p><sup>13/02/2012, by gringo@test.com</sup></p>
				<p>A determinate progress bar should never fill from left to right, then loop back to empty for a single process -- if the actual percent complete status cannot be calculated, an indeterminate progress bar (coming soon)...</p>
			</li>
			<li style="margin: .4em 0">
				<p>
					<span style="float:right">
						<a href="">Publish</a>
						<a href="">Delete</a>
					</span>
					<a href="">Lorem ipsum dolor sit amec...</a>
				</p>
				<p><sup>13/02/2012, by gringo@test.com</sup></p>
				<p>This is a determinate progress bar, meaning that it should only be used in situations where the system can accurately update the current status complete</p>
			</li>
		</ol>
	</div>
    <h3><a href="#">Most popular posts</a></h3>
    <div>
		<ol>
			<li style="margin: .4em 0">
				<p>
					<span style="float:right; padding-right: .5em; font-size: .8em">
						<a href="">Unpublish</a>
						<a href="">Delete</a>
					</span>
					<a href="">The bar is coded to be flexibly sized through CSS</a>
				</p>
			</li>
			<li style="margin: .4em 0">
				<p>
					<span style="float:right; padding-right: .5em; font-size: .8em">
						<a href="">Unpublish</a>
						<a href="">Delete</a>
					</span>
					<a href="">A determinate progress bar should never fill from left to right, then loop back to empty for a single process</a>
				</p>
			</li>
		</ol>
	</div>
</div>
<script type="text/javascript">
	$('#blog_accordion').accordion()
</script>