<h3><?php echo \Z::__('Different column layouts', 'cms'); ?></h3>
<?php echo \Z::getHelper('Sys\Helper\Html')->link('cms/index', 'CMS index'); ?> |
<?php echo \Z::getHelper('Sys\Helper\Html')->link('cms/ajax', '1 column'); ?> |
<?php echo \Z::getHelper('Sys\Helper\Html')->link('cms/ajax2', '2 columns'); ?> |
<?php echo \Z::getHelper('Sys\Helper\Html')->link('cms/ajax', 'Ajax call', 'id="ajax1"'); ?>