<div class="grid widget" id="widget_<?php echo $this->getHtmlId(); ?>">
	<div class="widget-header" data-role="header">
		<h1><?php echo $this->getHeader()->getTitle(); ?></h1>
			<ul data-role="listview">
			<?php foreach ($this->getHeader()->getButtons() as $_button): ?>
				<li><?php echo $_button->getContent(); ?></li>
			<?php endforeach; ?>
			</ul>
	</div>
	<form method="post" action="<?php echo $this->getActionUrl();?>" id="<?php echo $this->getHtmlId(); ?>">
		<div data-role="footer" class="ui-grid-b">
			<div class="ui-block-a">
				<div class="text-align-right">
					<?php echo $this->__('Page') ?>
					<?php $_curPage  = $this->getCollection()->getCurPage(); ?>
					<?php $_lastPage = $this->getCollection()->getLastPageNumber(); ?>
					<?php if($_curPage>1): ?>
						<a href="#" title="<?php echo $this->__('Previous page') ?>" onclick=""><img src="<?php echo $this->getSkinUrl('images/icons/arrow_prev.png') ?>" alt="<?php echo $this->__('Go to previous page') ?>" class="arrow"/></a>
					<?php else: ?>
						<img src="<?php echo $this->getSkinUrl('images/icons/arrow_prev_dis.png') ?>" alt="<?php echo $this->__('Go to previous page') ?>" class="arrow"/>
					<?php endif; ?>
				</div>
			</div>

			<div class="ui-block-b">
				<input type="text" name="<?php echo $this->_varNamePage; ?>" size="3" value="<?php echo $_curPage ?>" class="input-text page" onkeypress=""/>
			</div>

			<div class="ui-block-c">
				<div class="text-align-left">
					<?php if($_curPage < $_lastPage): ?>
						<a href="#" title="<?php echo $this->__('Next page') ?>" onclick=""><img src="<?php echo $this->getSkinUrl('images/icons/arrow_next.png') ?>" alt="Go to Next page" class="arrow"/></a>
					<?php else: ?>
						<img src="<?php echo $this->getSkinUrl('images/icons/arrow_next_dis.png') ?>" alt="<?php echo $this->__('Go to next page') ?>" class="arrow"/>
					<?php endif; ?>

					<?php echo $this->__('of '.$_lastPage.' pages'); ?>
				</div>
			</div>
		</div>

		<div data-role="footer" class="ui-grid-b">
			<div class="ui-block-a">
				<div class="text-align-right">
					<select name="<?php echo $this->_varNameLimit; ?>" onchange="">
						<option value="10"<?php if($this->getCollection()->getPageSize()==10): ?> selected="selected"<?php endif; ?>>10</option>
						<option value="20"<?php if($this->getCollection()->getPageSize()==20): ?> selected="selected"<?php endif; ?>>20</option>
						<option value="30"<?php if($this->getCollection()->getPageSize()==30): ?> selected="selected"<?php endif; ?>>30</option>
						<option value="40"<?php if($this->getCollection()->getPageSize()==40): ?> selected="selected"<?php endif; ?>>40</option>
						<option value="50"<?php if($this->getCollection()->getPageSize()==50): ?> selected="selected"<?php endif; ?>>50</option>
					</select>
				</div>
			</div>
			<div class="ui-block-b">
				<div class="text-align-left">
					<?php echo $this->__('per page') ?>
				</div>
			</div>
			<div class="ui-block-c">
				<?php echo $this->__('Total %d records found', $this->getCollection()->getSize()) ?>
			</div>
		</div>

		<div>
			<select name="<?php echo $this->getHtmlId() ?>_export" id="<?php echo $this->getHtmlId() ?>_export" style="width:8em;">
				<option value="empty">Export option</option>
			</select>
			<?php echo $this->getExportButtonHtml() ?>
			<input type="reset" name="reset" data-icon="refresh" onclick="$('#<?php echo $this->getHtmlId(); ?>').clearForm().submit();" value="<?php echo $this->__('Reset filters'); ?>" />
			<input type="submit" name="submit" data-icon="search" value="<?php echo $this->__('Search'); ?>" />
		</div>
	<table class="widget_grid" id="table_<?php echo $this->getHtmlId(); ?>">
		<?php foreach ($this->getColumns() as $_column): ?>
		<col <?php echo $_column->getHeaderProperty(); ?>/>
		<?php endforeach; ?>
		<thead>
			<tr class="columns">
				<?php foreach ($this->getColumns() as $_column): ?>
				<th class="grid_column_header"><?php echo $_column->getHeader(); ?></th>
				<?php endforeach; ?>
			</tr>
			<tr class="filter">
				<?php foreach ($this->getColumns() as $_column): ?>
				<th><?php echo $_column->getFilterHtml(); ?></th>
				<?php endforeach; ?>
			</tr>
		</thead>
		<tbody>
			<?php if ($this->getCollection()->getSize() > 0): ?>
			<?php $start = 0; ?>
			<?php foreach ($this->getCollection() as $item): ?>
			<tr class="<?php echo ($start++ % 2 == 0) ? 'tr_odd' : 'tr_even';?>" >
				<?php foreach ($this->getColumns() as $_column): ?>
				<td><?php echo $_column->getContent($item); ?></td>
				<?php endforeach; ?>
			</tr>
			<?php endforeach; ?>
			<?php endif; ?>
		</tbody>
	</table>
	</form>
</div>
	<script type="text/javascript">
	$('#<?php echo $this->getHtmlId(); ?>').submit(function()
	{
		var options = {
			target: '#widget_<?php echo $this->getHtmlId(); ?>',
			beforeSubmit: showAjaxRequest,
			success: hideAjaxRequest
			};
		$(this).ajaxSubmit(options);
		//!!! Important !!!
		// always return false to prevent standard browser submit and page navigation
		return false;
	});
	</script>