<div class="grid widget" id="widget_<?php echo $this->getHtmlId(); ?>">
	<h2><?php echo $this->getHeader()->getTitle(); ?></h2>
	<div data-role="controlgroup">
	<?php foreach ($this->getHeader()->getButtons() as $_button): ?>
		<?php echo $_button->getContent(); ?>
	<?php endforeach; ?>
	</div>
	<form method="post" action="<?php echo $this->getActionUrl();?>" id="<?php echo $this->getHtmlId(); ?>">
		<div class="ui-grid-b">
			<div class="ui-block-a">
				<p class="text-align-right"><?php echo $this->__('Page') ?></p>
			</div>
			<div class="ui-block-b">
				<p class="text-align-center">
				<?php $_curPage  = $this->getCollection()->getCurPage(); ?>
				<?php $_lastPage = $this->getCollection()->getLastPageNumber(); ?>
				<?php if($_curPage>1): ?>
					<a href="#" title="<?php echo $this->helper('admin')->__('Previous page') ?>" onclick=""><img src="<?php echo $this->getSkinUrl('images/icons/arrow_prev.png') ?>" alt="<?php echo $this->helper('admin')->__('Go to previous page') ?>" class="arrow"/></a>
				<?php else: ?>
					<img src="<?php echo $this->getSkinUrl('images/icons/arrow_prev_dis.png') ?>" alt="<?php echo $this->helper('admin')->__('Go to previous page') ?>" class="arrow"/>
				<?php endif; ?>
				<input style="width: 100px; display: inline" type="text" name="<?php echo $this->_varNamePage; ?>" size="3" value="<?php echo $_curPage ?>" class="input-text page" onkeypress=""/>
				<?php if($_curPage < $_lastPage): ?>
					<a href="#" title="<?php echo $this->__('Next page') ?>" onclick=""><img src="<?php echo $this->getSkinUrl('images/icons/arrow_next.png') ?>" alt="Go to Next page" class="arrow"/></a>
				<?php else: ?>
					<img src="<?php echo $this->getSkinUrl('images/icons/arrow_next_dis.png') ?>" alt="<?php echo $this->__('Go to next page') ?>" class="arrow"/>
				<?php endif; ?>
				</p>
			</div>
			<div class="ui-block-c">
				<p><?php echo $this->helper('admin')->__('of '.$_lastPage.' pages'); ?></p>
			</div>
		</div>


		<div class="ui-grid-b">
			<div class="ui-block-a">
				<p class="text-align-right"><?php echo $this->helper('admin')->__('View');?></p>
			</div>
			<div class="ui-block-b">
				<select name="<?php echo $this->_varNameLimit; ?>" onchange="">
					<option value="10"<?php if($this->getCollection()->getPageSize()==10): ?> selected="selected"<?php endif; ?>>10</option>
					<option value="20"<?php if($this->getCollection()->getPageSize()==20): ?> selected="selected"<?php endif; ?>>20</option>
					<option value="30"<?php if($this->getCollection()->getPageSize()==30): ?> selected="selected"<?php endif; ?>>30</option>
					<option value="40"<?php if($this->getCollection()->getPageSize()==40): ?> selected="selected"<?php endif; ?>>40</option>
					<option value="50"<?php if($this->getCollection()->getPageSize()==50): ?> selected="selected"<?php endif; ?>>50</option>
				</select>
			</div>
			<div class="ui-block-c">
				<p><?php echo $this->helper('admin')->__('per page') ?> | <?php echo $this->helper('admin')->__('Total %d records found', $this->getCollection()->getSize()); ?></p>
			</div>
		</div>

		<div>
			<select name="<?php echo $this->getHtmlId() ?>_export" id="<?php echo $this->getHtmlId() ?>_export" style="width:8em;">
				<option value="empty">Export option</option>
			</select>
			<?php echo $this->getExportButtonHtml() ?>
			<div class="ui-grid-a">
				<div class="ui-block-a">
					<input type="reset" name="reset" data-icon="gear" onclick="$('#filter_<?php echo $this->getHtmlId(); ?>').show();" value="<?php echo $this->__('Modify filters'); ?>" />
				</div>
				<div class="ui-block-b">
					<input type="reset" name="reset" data-icon="refresh" onclick="$('#<?php echo $this->getHtmlId(); ?>').clearForm().submit();" value="<?php echo $this->helper('admin')->__('Reset filters'); ?>" />
				</div>
			</div>
			<input type="submit" data-theme="b" name="submit" data-icon="search" value="<?php echo $this->helper('admin')->__('Search'); ?>" />
		</div>

		<div id="filters_<?php echo $this->getHtmlId(); ?>" style="display: none">
			<h2><?php echo $this->__('Apply filters'); ?></h2>
			<table class="widget_grid">
			<?php foreach ($this->getColumns() as $_column): ?>
				<tr class="filter">
					<th>
						<?php echo $_column->getHeader(); ?>
					</th>
					<td>
						<?php echo $_column->getFilterHtml(); ?>
					</td>
				</tr>
			<?php endforeach; ?>
			</table>
		</div>
	
		<h3><?php echo $this->__('Results'); ?></h3>
		<div class="ui-body">

		<ul data-role="listview">
			<?php if ($this->getCollection()->getSize() > 0): ?>
			<?php $start = 0; ?>
			<?php foreach ($this->getCollection() as $item): ?>
			<li	data-theme="<?php echo ($start++ % 2 == 0) ? 'a': 'b'; ?>">
				<a href="<?php echo $this->getUrl('*/*/edit')?>">
				<?php foreach ($this->getColumns() as $_column): ?>
				<div class="ui-grid-a">
					<div class="ui-block-a"><?php echo $_column->getHeader(); ?></div>
					<div class="ui-block-b"><?php echo $_column->getContent($item); ?></div>
				</div>
				<?php endforeach; ?>
				</a>
			</li>
			<?php endforeach; ?>
			<?php endif; ?>
		</ul>
	</div>

	</form>
</div>
<script type="text/javascript">
	$('#<?php echo $this->getHtmlId(); ?>').submit(function()
	{
		var options = {
			target: '#widget_<?php echo $this->getHtmlId(); ?>',
			//beforeSubmit: showAjaxRequest,
			success: function() { $('#widget_<?php echo $this->getHtmlId(); ?>').trigger('create'); }
			};
		$(this).ajaxSubmit(options);
		//!!! Important !!!
		// always return false to prevent standard browser submit and page navigation
		return false;
	});
</script>