<?php $startId =  $this->getHtmlId().'_from'; ?>
<?php $endId   =  $this->getHtmlId().'_to'; ?>
<div class="grid-input-medium">
	<label for="<?php echo $startId; ?>"><?php echo $this->__('From'); ?></label>
	<input class="input-text" type="text" name="<?php echo $this->getFieldName(); ?>[from]" id="<?php echo $startId; ?>" value="<?php echo $this->getEscapedValue('from'); ?>" />
</div>
<div class="grid-input-medium">
	<label for="<?php echo $endId; ?>"><?php echo $this->__('To'); ?></label>
	<input class="input-text" type="text" name="<?php echo $this->getFieldName(); ?>[to]" id="<?php echo $endId; ?>" value="<?php echo $this->getEscapedValue('to'); ?>" />
</div>
<script>
	$(function() {
		$("#<?php echo $startId; ?>").datepicker({defaultDate: null});
		$("#<?php echo $endId; ?>").datepicker({defaultDate: null});
	});
</script>