<!DOCTYPE html>
<html>
	<head>
		<?php echo $this->getChildHtml('head'); ?>
	</head>
	<body>
		<?php echo $this->getChildHtml('after_body_start'); ?>
		<div id="container" class="container">
			<?php echo $this->getChildHtml('notices'); ?>
			<div id="header" class="header">
				<?php echo $this->getChildHtml('header'); ?>
			</div>
			<div id="content_wrapper">
				<div id="content">
					<?php echo $this->getChildHtml('content'); ?>
				</div>
				<div id="content_right">
					<?php echo $this->getChildHtml('right'); ?>
				</div>
			</div>
			<div id="footer">
				<?php echo $this->getChildHtml('footer'); ?>
			</div>
			<div id="status_bar">
				<?php echo $this->getChildHtml('status_bar'); ?>
			</div>
		</div>

		<div id="messages" class="messages">
			<?php echo $this->getChildHtml('messages'); ?>
		</div>
	</body>
</html>