<?php
/**
 * Base Block class, used by layouts
 *
 * @author radu.mogos
 */

namespace Sys\Layout
{
	class Block
	{
		/**
		 * Holds an array of \Sys\Block chidren
		 * @var <array> 
		 */
		protected $children = array();

		/**
		 * The block's name
		 * @var <string>
		 */
		protected $name;

		/**
		 * The template name used by the block for content rendering, if required
		 * @var <string>
		 */
		protected $template;
		
		/**
		 * The actual template resource (php code for the view)
		 * @var <string>
		 */
		protected $templateResource;

		/**
		 * The PHP/HTML code loaded from the block's template
		 * @var <type>
		 */
		protected $code;

		public function __construct($name, \SimpleXMLElement $xml)
		{
			$this->children = array();
			$this->name = $name;
			$this->templateResource = NULL;
			$this->code = NULL;
			$this->setTemplate((string)$xml["template"]);
		}

		/**
		 * Adds a children to the children list
		 * @param \Sys\Layout\Block $value 
		 */
		public function addChildren(\Sys\Layout\Block $value)
		{
			$this->children[$value->getName()] = $value;
		}

		// processing

		/**
		 * Get the relative view path
		 *
		 * @return <string> the relative path to the app/views directory
		 */
		protected function getPath()
		{
			return \App\Config\System::APP_DIR.DIRECTORY_SEPARATOR.'views'.DIRECTORY_SEPARATOR.'blocks'.DIRECTORY_SEPARATOR;
		}

		/**
		 * @param <string> $template the location + name of the template file
		 * @return <Sys\Layout\Block> reference to the current instance
		 */
		public function loadTemplate($template = '')
		{
			if ($template != '')
			{
				$this->template = $this->getPath().$template;
				$filesize = filesize($this->template);
				$file = fopen($this->template, 'r');
				$this->code = fread($file, $filesize);
				fclose($file);
			}
			//else
			//	throw new \Sys\Exception('Block file missing: Please specify the block template filename!');
			return $this;
		}

		/**
		 * Render the current php/html block
		 * @return <string> The final generated HTML code
		 */
		public function render()
		{
			if ($this->code !== NULL)
			{
				ob_start();
				eval("?>".$this->code);
				$renderedCode = ob_get_contents();
				ob_end_clean();
				return $renderedCode;
			}
			else
				return '';
		}

		/**
		 * Render a block and all it's children
		 * @param <string> $childName The name of the parent block
		 * @return <string> The HTML code generated by executing all the children blocks
		 */
		public function getChildHtml($childName)
		{
			if (!array_key_exists($childName, $this->children))
				throw new \Sys\Exception("Error in: $this->template. Make sure the child block '$childName' with parent block '$this->name' is defined in the xml file.");
			$child = $this->children[$childName];
			$html = '';
			/*if ($child->getChildrenCount() > 0)
			{
				foreach ($child->getChildren() as $block)
				{
					$html .= $block->render();
				}
			}
			else*/
				$html = $child->render();
			return $html;
		}

		/**
		 * Return the number of children blocks this parent block has
		 * @param <string> $childName If you want to return the block count for another block, instead of the current one, specify it's name
		 * @return <int> Number of children blocks
		 */
		public function getChildrenCount($childName = '')
		{
			if ($childName != '')
			{
				return count($this->children[$childName]->getChildren());
			}
			return count($this->children);
		}

		/**
		 * Return a child block by it's name
		 * @param <string> $name The name of the child block to return
		 * @return <Sys\Layout\Block> An instance of Block classs
		 */
		public function getChild($name)
		{
			return $this->children[$name];
		}

		/**
		 * Remove a child from the list of children blocks
		 * @param <string> $name The child name to remove
		 */
		public function unsetChild($name)
		{
			unset($this->children[$name]);
		}

		// getters, setters

		public function getChildren()
		{
			return $this->children;
		}

		public function setChildren($value)
		{
			$this->children = $value;
		}

		public function setName($value)
		{
			$this->name = $value;
		}

		public function getName()
		{
			return $this->name;
		}

		public function setTemplate($value)
		{
			//$this->template = $value;
			$this->loadTemplate($value);
		}

		public function getTemplate()
		{
			return $this->template;
		}

		public function getCode()
		{
			return $this->code;
		}

		public function setCode($value)
		{
			$this->code = $value;
		}
	}
}
