<?php $startId =  $this->getFieldName().'_from'; ?>
<?php $endId   =  $this->getFieldName().'_to'; ?>
<div data-role="fieldcontain">
	<label for="<?php echo $startId; ?>"><?php echo $this->__('From'); ?></label>
	<input type="text" name="<?php echo $this->getFieldName(); ?>[from]" id="<?php echo $startId; ?>" value="" />
</div>
<div data-role="fieldcontain">
	<label for="<?php echo $endId; ?>"><?php echo $this->__('To'); ?></label>
	<input type="text" name="<?php echo $this->getFieldName(); ?>[to]" id="<?php echo $endId; ?>" value="" />
</div>
<script>
	$(function() {
		$("#<?php echo $startId; ?>").datepicker({defaultDate: null});
		$("#<?php echo $endId; ?>").datepicker({defaultDate: null});
	});
</script>