<!DOCTYPE html>
<html>
	<head>
		<?php echo $this->getChildHtml('head'); ?>
	</head>
	<body>
		<div id="page-main" class="page-main">
			<div data-role="header" data-theme="c">
				<?php echo $this->getChildHtml('header'); ?>
			</div>
			<div id="page-messages">
				<?php echo $this->getChildHtml('messages'); ?>
			</div>
			<div class="page-content">
				<?php echo $this->getChildHtml('content'); ?>
			</div>
			<div class="footer" id="page-footer">
				<?php echo $this->getChildHtml('footer'); ?>
			</div>
		</div>
	</body>
</html>