						<dt>Comenzi noi</dt>
						<dd id="status-scanerrors" class="status-bar-popup" style = "">
							<a href="javascript:void(0)" class="scan_errors" id="indicator-scan_errors"><span>21</span></a>
						</dd>

						<dt>Notificări</dt>
						<dd id="status-plugins" class="status-bar-popup selected" style = "">

							<a href="javascript:void(0)" class="plugins" id="indicator-plugins"><span>2</span></a>
							<div style="" class="popup">
								<h5 class="header">
									Ultimele notificări
									<a href="javascript:void(0)" class="close">close</a>
								</h5>
								<div class="content-filterbar"></div>
								<div id="" class="content">

									<ul class="sui-status-list">
										<li id="" class="recommendation dismissable">
											<img src="images/admin/icons/help.png"/>
											<a class="sui-list-dismiss" title="Dismiss this recommendation" href="">Delete</a>
											<h4 class="title">
												<a href="">Update de securitate 1.3?</a>
											</h4>
											<div class="message">

												<a href="">raduangelescu</a>
											</div>
											<p class="bottom">
												Postat la <strong>17 Oct 2011 06:59:50</strong>
											</p>
										</li>
										<li id="" class="scan_alert unknown filterable filter-unknown">

											<img src="images/admin/icons/messages.png"/>
											<a class="sui-list-dismiss" title="Dismiss this recommendation" href="">Delete</a>
											<h4 class="title">
												<a href="">Ce să faci și ce să nu faci!</a>
											</h4>
											<div class="message">
												<a href="">nekitu</a>, <a href="">eosforfly</a>, <a href="">nekosan</a>, <a href="">pauliancu_97</a>

											</div>
											<p class="bottom">
												Postat la <strong>17 Oct 2011 08:22:10</strong>
											</p>
										</li>
									</ul>
								</div>
								<div style="display: none;" class="actionBox"></div>

								<div style="display: none;" class="alertBox"></div>
								<div style="" class="footer"><a href="/settings/plugins">View Plugins</a></div>
						</dd>
						<dt>Ultimele extensii</dt>
						<dd id="status-scanerrors" class="status-bar-popup">
							<a href="javascript:void(0)" class="icon_extension_upgrades" id="indicator-scan_errors"><span>1</span></a>
						</dd>