<?php switch ($this->getType()) {
    case 'hidden': ?>
		<input type="<?php echo $this->getType() ?>" name="<?php echo $this->getIndex() ?>" id="<?php echo $this->getHtmlId() ?>" value="<?php echo $this->getValue() ?>">
	<?php break;
    case 'select': ?>
		<td class="label"><?php if ($this->getLabel()): ?><label for="<?php echo $this->getHtmlId() ?>"><?php echo $this->getLabel() ?>:</label><?php endif; ?></td>
		<td>
		<?php echo $this->getElementHtml(); ?>
		<?php echo $this->getAfterElementHtml(); ?>
		</td>
	<?php break;
    case 'text':
    case 'button':
    case 'password': ?>
		<td class="label"><?php if($this->getLabel()): ?><label for="<?php echo $this->getHtmlId() ?>"><?php echo $this->getLabel() ?>:</label><?php endif; ?></td>
		<td><input type="<?php echo $this->getType() ?>" name="<?php echo $this->getIndex() ?>" id="<?php echo $this->getHtmlId() ?>" value="<?php echo $this->getValue() ?>" class="input-text <?php echo $this->getClass() ?>" title="<?php echo $this->getTitle() ?>" <?php echo ( $this->getOnClick() ? 'onClick="'.$this->getOnClick().'"' : '' ) ?>/>
			<?php echo $this->getAfterElementHtml(); ?>
		</td>
	<?php break;
    case 'radio': ?>
		<td class="label"><?php if($this->getLabel()): ?><label for="<?php echo $this->getHtmlId() ?>"><?php echo $this->getLabel() ?>:</label><?php endif; ?></td>
		<td><input type="<?php echo $this->getType() ?>" name="<?php echo $this->getIndex() ?>" id="<?php echo $this->getHtmlId() ?>" value="<?php echo $this->getValue() ?>" class="input-text <?php echo $this->getClass() ?>" title="<?php echo $this->getTitle() ?>"/>
			<?php echo $this->getAfterElementHtml(); ?>
		</td>
	<?php break;
    case 'radios': ?>
		<td class="label"><label for="<?php echo $this->getHtmlId() ?>"><?php echo $this->getLabel() ?>:</label></td>
		<td>
		<?php foreach($this->getRadios() as $_radio): ?>
		<input type="radio" name="<?php echo $_radio->getName() ?>" id="<?php echo $_radio->getHtmlId() ?>" value="<?php echo $_radio->getValue() ?>" class="input-radio <?php echo $_radio->getClass() ?>" title="<?php echo $_radio->getTitle() ?>" <?php echo ( $_radio->getValue() == $this->getChecked() ) ? 'checked="true"' : '' ?> >&nbsp;<?php echo $_radio->getLabel() ?>
		<?php endforeach; ?>
		<?php echo $this->getAfterElementHtml(); ?>
		</td>
	<?php break;
	case 'editor':
    case 'wysiwyg': ?>
		<td class="label"><label for="<?php echo $this->getHtmlId() ?>"><?php echo $this->getLabel() ?>:</label></td>
		<td><textarea name="<?php echo $this->getIndex() ?>" title="<?php echo $this->getTitle() ?>" id="<?php echo $this->getHtmlId() ?>" class="textarea editor <?php echo $this->getClass() ?>" cols="60" rows="20"><?php echo $this->getValue(); ?></textarea>
			<?php echo $this->getAfterElementHtml(); ?>
		</td>
	<?php break;
	case 'textarea': ?>
		<td class="label"><label for="<?php echo $this->getHtmlId() ?>"><?php echo $this->getLabel() ?>:</label></td>
		<td><textarea name="<?php echo $this->getIndex() ?>" title="<?php echo $this->getTitle() ?>" id="<?php echo $this->getHtmlId() ?>" class="textarea <?php echo $this->getClass() ?>" cols="15" rows="2"><?php echo $this->getValue(); ?></textarea>
			<?php echo $this->getAfterElementHtml(); ?>
		</td>
	<?php break;
    case 'file': ?>
      <?php break;
    case 'checkbox': ?>
      <?php break;
} ?>
<?php if($this->getScript()): ?>
<script type="text/javascript">
    <?php echo $this->getScript() ?>
</script>
<?php endif; ?>
