<div class="grid widget" id="widget_<?php echo $this->getHtmlId(); ?>">
	<div class="widget-header">
		<div class="widget_header_buttons">
			<?php echo $this->getHeader()->getButtonsHtml(); ?>
		</div>
		<h1><?php echo $this->getHeader()->getTitle(); ?></h1>
	</div>
	<form method="post" action="<?php echo $this->getActionUrl();?>" id="<?php echo $this->getHtmlId(); ?>">
		<input type="hidden" name="<?php echo $this->_varNameSort; ?>" value="<?php echo $this->getParam($this->_varNameSort, $this->_defaultSort);?>" />
		<input type="hidden" name="<?php echo $this->_varNameDir; ?>" value="<?php echo $this->getParam($this->_varNameDir, $this->_defaultDir);?>" />
	<table class="widget_grid_pager">
		<tr>
			<td>
				<?php echo $this->helper('admin')->__('Page') ?>
				<?php $_curPage  = $this->getCollection()->getCurPage(); ?>
				<?php $_lastPage = $this->getCollection()->getLastPageNumber(); ?>
				<?php if ($_curPage > $_lastPage) { $_curPage = 1;} ?>
				<?php if($_curPage>1): ?>
					<a id="prev_<?php echo $this->getHtmlId(); ?>" href="<?php echo $this->getEncodedUrl(array($this->_varNamePage => $_curPage - 1)); ?>" title="<?php echo $this->helper('admin')->__('Previous page') ?>" onclick=""><img src="<?php echo $this->getSkinUrl('images/icons/arrow_prev.png') ?>" alt="<?php echo $this->helper('admin')->__('Go to previous page') ?>" class="arrow"/></a>
				<?php else: ?>
					<img src="<?php echo $this->getSkinUrl('images/icons/arrow_prev_dis.png') ?>" alt="<?php echo $this->helper('admin')->__('Go to previous page') ?>" class="arrow"/>
				<?php endif; ?>

				<input id="page_<?php echo $this->getHtmlId(); ?>" type="text" name="<?php echo $this->_varNamePage; ?>" size="3" value="<?php echo $_curPage ?>" class="input-text page"/>

				<?php if($_curPage < $_lastPage): ?>
					<a id="next_<?php echo $this->getHtmlId(); ?>" href="<?php echo $this->getEncodedUrl(array($this->_varNamePage => $_curPage + 1)); ?>" title="<?php echo $this->helper('admin')->__('Next page') ?>" onclick=""><img src="<?php echo $this->getSkinUrl('images/icons/arrow_next.png') ?>" alt="Go to Next page" class="arrow"/></a>
				<?php else: ?>
					<img src="<?php echo $this->getSkinUrl('images/icons/arrow_next_dis.png') ?>" alt="<?php echo $this->helper('admin')->__('Go to next page') ?>" class="arrow"/>
				<?php endif; ?>

				<?php echo $this->helper('admin')->__('of %s pages', $_lastPage); ?>

					<span class="separator">|</span>
					<?php echo $this->helper('admin')->__('View') ?>
					<select name="<?php echo $this->_varNameLimit; ?>" onchange="">
						<option value="1"<?php if($this->getCollection()->getPageSize()==1): ?> selected="selected"<?php endif; ?>>1</option>
						<option value="20"<?php if($this->getCollection()->getPageSize()==20): ?> selected="selected"<?php endif; ?>>20</option>
						<option value="30"<?php if($this->getCollection()->getPageSize()==30): ?> selected="selected"<?php endif; ?>>30</option>
						<option value="40"<?php if($this->getCollection()->getPageSize()==40): ?> selected="selected"<?php endif; ?>>40</option>
						<option value="50"<?php if($this->getCollection()->getPageSize()==50): ?> selected="selected"<?php endif; ?>>50</option>
					</select>
					<?php echo $this->helper('admin')->__('per page') ?> <span class="separator">|</span>

				<?php echo $this->helper('admin')->__('Total %d records found', $this->getCollection()->getCount()) ?>
			</td>
			<td class="export a-right">
				<img src="<?php echo $this->getSkinUrl('images/icons/export.png') ?>" alt="" class="v-middle"/>&nbsp; <?php echo $this->helper('admin')->__('Export to:') ?>
				<select name="<?php echo $this->getHtmlId() ?>_export" id="<?php echo $this->getHtmlId() ?>_export" style="width:8em;">
					<option value="empty">Export option</option>
				</select>
				<?php echo $this->getExportButtonHtml() ?>
			</td>
			<td class="a-right">
				<input type="reset" name="reset" onclick="$('#<?php echo $this->getHtmlId(); ?>').clearForm().submit();" class="ui-icon-refresh" value="<?php echo $this->helper('admin')->__('Reset filters'); ?>" />
				<input type="submit" name="submit" class="ui-icon-search" value="<?php echo $this->helper('admin')->__('Search'); ?>" />
			</td>
		</tr>
	</table>
	<?php if($this->getMassactionBlock()->isAvailable()): ?>
		<?php echo $this->getChildHtml('massaction'); ?>
	<?php endif ?>
	<table class="widget_grid" id="table_<?php echo $this->getHtmlId(); ?>">
		<?php foreach ($this->getColumns() as $_column): ?>
		<col <?php echo $_column->getHeaderProperty(); ?>/>
		<?php endforeach; ?>
		<thead>
			<tr class="columns">
				<?php foreach ($this->getColumns() as $_column): ?>
				<th class="grid_column_header"><?php echo $_column->getHeader(); ?></th>
				<?php endforeach; ?>
			</tr>
			<tr class="filter">
				<?php foreach ($this->getColumns() as $_column): ?>
				<th><?php echo $_column->getFilterHtml(); ?></th>
				<?php endforeach; ?>
			</tr>
		</thead>
		<tbody>
			<?php if ($this->getCollection()->getSize() > 0): ?>
			<?php $start = 0; ?>
			<?php foreach ($this->getCollection() as $item): ?>
			<tr class="<?php echo ($start++ % 2 == 0) ? 'tr_odd' : 'tr_even';?>" >
				<?php foreach ($this->getColumns() as $_column): ?>
				<td><?php echo $_column->getContent($item); ?></td>
				<?php endforeach; ?>
			</tr>
			<?php endforeach; ?>
			<?php else: ?>
			<tr>
				<td class="grid-no-records" colspan="99">
					<p><?php echo $this->helper('admin')->__('There are no records matching your criteria.'); ?></p>
				</td>
			</tr>
			<?php endif;?>
		</tbody>
	</table>
	</form>
</div>
	<script type="text/javascript">
	$('#<?php echo $this->getHtmlId(); ?>').submit(function()
	{
		var options = {
			target: '#widget_<?php echo $this->getHtmlId(); ?>',
			beforeSubmit: showAjaxRequest,
			// if javascript is disabled the non ajax url is called by default
			url: '<?php echo $this->getAjaxActionUrl(); ?>',
			success: hideAjaxRequest
			};
		$(this).ajaxSubmit(options);
		//!!! Important !!!
		// always return false to prevent standard browser submit and page navigation
		return false;
	});
	$('#next_<?php echo $this->getHtmlId(); ?>').bind('click', function() {
		$('#page_<?php echo $this->getHtmlId(); ?>').val(parseInt($('#page_<?php echo $this->getHtmlId(); ?>').val()) + 1);
		$('#<?php echo $this->getHtmlId(); ?>').submit();
		return false;
	});
	$('#prev_<?php echo $this->getHtmlId(); ?>').bind('click', function() {
		$('#page_<?php echo $this->getHtmlId(); ?>').val(parseInt($('#page_<?php echo $this->getHtmlId(); ?>').val()) - 1);
		$('#<?php echo $this->getHtmlId(); ?>').submit();
		return false;
	});
	</script>